# Generated by Django 5.1.3 on 2024-11-21 22:42

from django.contrib.postgres.operations import TrigramExtension # added
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
        TrigramExtension() # added
    ]
